apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-in-prod
  namespace: prod
spec:
  generators:
    - list:
        elements:
          - name: adservice
            path: adservice
          - name: cartservice
            path: cartservice
          - name: checkoutservice
            path: checkoutservice
          - name: currencyservice
            path: currencyservice
          - name: emailservice
            path: emailservice
          - name: frontend
            path: frontend
          - name: common_helm
            path: common_helm
          - name: loadgenerator
            path: loadgenerator
          - name: paymentservice
            path: paymentservice
          - name: productcatalogservice
            path: productcatalogservice
          - name: recommendationservice
            path: recommendationservice
          - name: shippingservice
            path: shippingservice
  template:
    metadata:
      name: '{{name}}-prod'
    spec:
      project: default
      source:
        repoURL: https://github.com/vvkgdm/ProjectXHelm.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values-prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: prod
      syncPolicy: {}  # Automated sync is not configured for PROD
